# Generated by Django 5.1.2 on 2026-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_pv_post_uv"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_html",
            field=models.TextField(blank=True, editable=False, verbose_name="正文html代码"),
        ),
    ]
