# Generated by Django 5.1.2 on 2026-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target",
            field=models.CharField(max_length=100, verbose_name="评论目标"),
        ),
    ]
